version: '3.8'
# network ismini belirler. Belirtilmezse bulunduğu klasör ismini alır.
# : sonrasıda tipini belirtir.
# birden fazla network kullanılabilir.
networks:
    5g_core_network:
      driver: bridge
      ipam:
        config:
          - subnet: 1.1.1.0/24
            gateway: 1.1.1.1

services:
  ans:
    working_dir: /root/proje
    build:
      dockerfile: Dockerfile-ansible
      context: .
    working_dir: /root/proje
    image: cemt/ansible
    # image: ansible:latest
    container_name: ans
    privileged: true
    command: tail -f /dev/null
    # Ansible ayarlarını (ansible.cfg) ve 
    # hedef bilgisayar bilgilerini (hosts) tutan dosyaları 
    # korumak adına volumes altında bağlayalım: 
    volumes: 
      - ./calisma_dizini/ansible_ayarlari/ansible.cfg:/etc/ansible/ansible.cfg
      - ./calisma_dizini/ansible_ayarlari/hosts:/etc/ansible/hosts
      - ./calisma_dizini/proje/:/root/proje/
    networks:
        5g_core_network:
          ipv4_address: 1.1.1.2

  ssh_3:
    build:
      dockerfile: Dockerfile-ubuntu-sshd
      context: .
    image: cemt/bionic-sshd
    container_name: ssh_3
    networks:
        5g_core_network:
          ipv4_address: 1.1.1.3

  ssh_4:
    image: rastasheep/ubuntu-sshd
    container_name: ssh_4
    networks:
        5g_core_network:
          ipv4_address: 1.1.1.4

  mc_gms:
    image: rastasheep/ubuntu-sshd
    container_name: gms
    networks:
        5g_core_network:
          ipv4_address: 1.1.1.5
  mc_csc:
    image: rastasheep/ubuntu-sshd
    container_name: csc
    networks:
        5g_core_network:
          ipv4_address: 1.1.1.6

  mc_ptt:
    image: rastasheep/ubuntu-sshd
    container_name: ptt
    networks:
        5g_core_network:
          ipv4_address: 1.1.1.7

  mc_video:
    image: rastasheep/ubuntu-sshd
    container_name: mcvideo
    networks:
        5g_core_network:
          ipv4_address: 1.1.1.8


  # sunucu2:
  #   image: ubuntu:xenial
  #   container_name: sunucu2
  #   privileged: true
  #   command: '/sbin/init'
  #   networks:
  #       5g_core_network:
  #         ipv4_address: 1.1.1.4
